main: com.winthier.creative.CreativePlugin

name: Creative
description: Manage Creative Worlds
author: StarTux
version: 0.1
website: https://github.com/StarTux/Creative
api-version: 1.17

depend: [Core, WorldEdit, PlayerCache, GenericEvents, VoidGenerator, FlatGenerator]
softdepend: []

commands:
  world:
    aliases: [ worlds ]
    description: User interface
    permission: creative.world
    usage: |-
      /world list - List your worlds
      /world visit - List worlds you can join
      /world info - Get world info
      /world buy [type] - Buy a world
      /world unlock - Unlock world features
      /world grow - Grow your world
      /world spawn - Teleport to spawn
      /world setspawn - Set world spawn
      /world rename <name> - Rename world
      /world time [time] - Get or set the world time
      /world difficulty [difficulty] - Difficulty setting
      /world gamemode <gamemode> - Change your GameMode
      /world trust <player> [trust] - Trust someone
      /world untrust <player> - Revoke trust
      /world confirm - Confirm action
      /world cancel - Cancel action
  wtp:
    description: World Teleport
    permission: creative.world
    usage: /wtp <world>
  creativeadmin:
    aliases: [ ca ]
    description: Admin Interface
    permission: creative.admin
    usage: |-
      /ca ignore - Toggle permission ignore
      /ca info [world] - World info
      /ca set [world] <key> <value> - World settings
      /ca list <player>
      /ca listloaded
      /ca tp [player] <world>
      /ca debug
      /ca remove <world>
      /ca trust <world> <player> <trust>
      /ca resetowner [world]
      /ca setowner <world> <player>
      /ca createvoid <name> [environment] - Create empty world
      /ca create
        n:name
        p:path
        o:owner
        g:generator
        G:generatorSettings
        e:environment
        t:worldType
        s:seed
        S:generateStructures
      /ca import <world>
      /ca load <world>
      /ca unload <world>
      /ca setwarp <name> - Set warp at player location
      /ca deletewarp <name> - Delete warp
  warp:
    description: Warps
    permission: creative.warp
    usage: |-
      /warp [name]
  plot:
    aliases: [plots]
    description: Plot interface
    permission: creative.world
    usage: |-
      /plot list - List your plots
      /plot warp <id> - Warp to plot
  area:
    aliases: []
    description: Area setup command
    permission: creative.area
    usage: |-
      /area list [file] - List areas
      /area highlight <file> <name> - Highlight areas
      /area add <file> <name> - Create new area from WE
      /area remove <file> <name> - Remove area you are in
permissions:
  creative.world:
    descrption: Use /world and /wtp
    default: op
  creative.warp:
    descrption: Use /warp
    default: op
  creative.admin:
    description: Use /CreativeAdmin
    default: op
  creative.worldedit:
    description: Use WorldEdit in the appropriate worlds
    default: op
  creative.world.buy:
    description: Buy a creative world
    default: op