main: com.winthier.creative.CreativePlugin
name: Creative

version: 0.1
api-version: '1.21'

description: Manage Creative Worlds
author: StarTux
website: https://github.com/StarTux/Creative

depend:
- Core
- SQL
- Mytems
softdepend:
- Shutdown
- WorldEdit
- VoidGenerator
- FlatGenerator

commands:

  creative:
    aliases: [cr]
    description: User interface
    permission: creative.creative
    usage: |-
      /cr list - List your worlds
      /cr visit - List worlds you can join
      /cr info - Get world info
      /cr buy [type] [dimension] - Buy a world
      /cr unlock - Unlock world features
      /cr grow - Grow your world
      /cr spawn - Teleport to spawn
      /cr setspawn - Set world spawn
      /cr rename <name> - Rename world
      /cr time [time] - Get or set the world time
      /cr difficulty [difficulty] - Difficulty setting
      /cr gamemode <gamemode> - Change your GameMode
      /cr trust <player> [trust] - Trust someone
      /cr untrust <player> - Revoke trust
      /cr confirm - Confirm action
      /cr cancel - Cancel action

  creativeadmin:
    aliases: [cra]
    description: Admin Interface
    permission: creative.admin
    usage: |-
      /cra ignore - Toggle permission ignore
      /cra info [world] - World info
      /cra set [world] <key> <value> - World settings
      /cra list <player>
      /cra listloaded
      /cra tp [player] <world>
      /cra debug
      /cra remove <world>
      /cra trust <world> <player> <trust>
      /cra resetowner [world]
      /cra setowner <world> <player>
      /cra createvoid <name> [environment] - Create empty world
      /cra create
        n:name
        p:path
        o:owner
        g:generator
        G:generatorSettings
        e:environment
        t:worldType
        s:seed
        S:generateStructures
      /cra import <world>
      /cra load <world>
      /cra unload <world>
      /cra autoconvert - Auto convert worlds
      /cra transferall <from> <to> - Transfer all worlds

  ctp:
    description: World Teleport
    permission: creative.creative
    usage: /ctp <world>

  ckit:
    aliases: []
    description: Open the Creative kit
    permission: creative.kit
    usage: /kit

  mapvote:
    aliases: []
    description: Vote on a map
    permission: creative.mapvote
    usage: /mapvote

permissions:

  creative.creative:
    descrption: Use /creative and /ctp
    default: op

  creative.admin:
    description: Use /cra
    default: op

  creative.worldedit:
    description: Use WorldEdit in the appropriate worlds
    default: op

  creative.buy:
    description: Buy a creative world
    default: op

  creative.kit:
    description: Use /ckit
    default: op

  creative.mapvote:
    description: Use /mapvote
    default: op