main: com.winthier.creative.CreativePlugin
name: Creative

version: 0.1
api-version: 1.19

description: Manage Creative Worlds
author: StarTux
website: https://github.com/StarTux/Creative

depend: [Core, WorldEdit, PlayerCache, VoidGenerator, FlatGenerator, Mytems]
softdepend: [Shutdown]

commands:

  world:
    aliases: [ worlds, creative ]
    description: User interface
    permission: creative.world
    usage: |-
      /world list - List your worlds
      /world visit - List worlds you can join
      /world info - Get world info
      /world buy [type] [dimension] - Buy a world
      /world unlock - Unlock world features
      /world grow - Grow your world
      /world spawn - Teleport to spawn
      /world setspawn - Set world spawn
      /world rename <name> - Rename world
      /world time [time] - Get or set the world time
      /world difficulty [difficulty] - Difficulty setting
      /world gamemode <gamemode> - Change your GameMode
      /world trust <player> [trust] - Trust someone
      /world untrust <player> - Revoke trust
      /world confirm - Confirm action
      /world cancel - Cancel action

  wtp:
    description: World Teleport
    permission: creative.world
    usage: /wtp <world>

  creativeadmin:
    aliases: [ ca, cra ]
    description: Admin Interface
    permission: creative.admin
    usage: |-
      /ca ignore - Toggle permission ignore
      /ca info [world] - World info
      /ca set [world] <key> <value> - World settings
      /ca list <player>
      /ca listloaded
      /ca tp [player] <world>
      /ca debug
      /ca remove <world>
      /ca trust <world> <player> <trust>
      /ca resetowner [world]
      /ca setowner <world> <player>
      /ca createvoid <name> [environment] - Create empty world
      /ca create
        n:name
        p:path
        o:owner
        g:generator
        G:generatorSettings
        e:environment
        t:worldType
        s:seed
        S:generateStructures
      /ca import <world>
      /ca load <world>
      /ca unload <world>
      /ca autoconvert - Auto convert worlds
      /ca transferall <from> <to> - Transfer all worlds

  plot:
    aliases: [plots]
    description: Plot interface
    permission: creative.world
    usage: |-
      /plot list - List your plots
      /plot warp <id> - Warp to plot

  kit:
    aliases: [ckit]
    description: Open the Creative kit
    permission: creative.kit
    usage: /kit

permissions:

  creative.world:
    descrption: Use /world and /wtp
    default: op

  creative.admin:
    description: Use /CreativeAdmin
    default: op

  creative.worldedit:
    description: Use WorldEdit in the appropriate worlds
    default: op

  creative.world.buy:
    description: Buy a creative world
    default: op

  creative.kit:
    description: Open the kit
    default: op